# Generated by Django 5.2.3 on 2025-06-27 12:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
import printery.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('address', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=25)),
                ('postal_code', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=56)),
                ('email', models.CharField(blank=True, max_length=64)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_manufacturer', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ctp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.IntegerField(blank=True, null=True)),
                ('plates_bad', models.IntegerField(blank=True, null=True)),
                ('plates_done_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'В работе'), ('issues', 'Проблемы с заказом'), ('completed', 'Сделан')], max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_employee', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to='printery.company')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=printery.models.Order.counter, unique=True)),
                ('name', models.CharField(blank=True, max_length=16)),
                ('type', models.CharField(blank=True, choices=[(None, 'Select...'), ('BK', 'Книга'), ('CL', 'Календарь'), ('MZ', 'Журнал'), ('NP', 'Газета'), ('FL', 'Флаер'), ('POS', 'Плакат'), ('INS', 'Инструкция')], max_length=3)),
                ('circulation', models.IntegerField(blank=True, null=True)),
                ('binding', models.CharField(blank=True, choices=[(None, 'Select...'), ('GLU', 'Glue'), ('STA', 'Staple'), ('HAR', 'Hardcover'), ('FOL', 'Folding')], max_length=4)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('submiting_files', models.DateTimeField(blank=True, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ManyToManyField(related_name='order_owners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=64)),
                ('type', models.CharField(choices=[('', 'Select...'), ('OFF', 'Офсетная'), ('GL', 'Глянцевая'), ('MAT', 'Матовая'), ('CAR', 'Картон')], max_length=3)),
                ('density', models.IntegerField(blank=True, choices=[(0, 'не известна'), (80, '80'), (100, '100'), (105, '105'), (115, '115'), (120, '120'), (130, '130'), (150, '150'), (170, '170'), (200, '200'), (250, '250'), (300, '300')], null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('manufacturer', models.ManyToManyField(blank=True, related_name='made_by', to='printery.company')),
            ],
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(blank=True, choices=[('BLO', 'блок'), ('COV', 'обложка'), ('INS', 'вклейка.'), ('FRZ', 'форзацы')], max_length=3)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('color', models.CharField(blank=True, choices=[(None, 'Select...'), ('4+4', '4+4'), ('4+0', '4+0'), ('1+1', '1+1'), ('1+0', '1+0')], max_length=3)),
                ('laminate', models.CharField(blank=True, choices=[(None, 'Select...'), ('MAT', 'Matte'), ('GL', 'Glossy')], max_length=3)),
                ('uflak', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='printery.order')),
                ('paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_paper', to='printery.paper')),
            ],
        ),
        migrations.CreateModel(
            name='PrintSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sm1', models.BooleanField(default=False)),
                ('sm2', models.BooleanField(default=False)),
                ('rapida', models.BooleanField(default=False)),
                ('printed_sheets', models.FloatField(blank=True, null=True)),
                ('circulation_sheets', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('parent_day', models.CharField(blank=True, max_length=20)),
                ('ctp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_schedule', to='printery.ctp')),
                ('order_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='printing', to='printery.part')),
            ],
        ),
        migrations.AddField(
            model_name='ctp',
            name='printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctp_related', to='printery.printschedule'),
        ),
    ]
