# Generated by Django 4.1.7 on 2023-04-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0004_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='submiting_files',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
