# Generated by Django 4.1.7 on 2023-05-08 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0005_order_submiting_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='owner',
            field=models.ManyToManyField(related_name='order_owners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='part',
            name='pages',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
