# Generated by Django 4.1.7 on 2023-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0006_alter_order_owner_alter_part_pages'),
        ('printery', '0006_alter_paper_manufacturer_alter_user_groups_and_more'),
    ]

    operations = [
    ]
