# Generated by Django 4.1.7 on 2023-07-26 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0007_merge_20230727_0054'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Printing',
            new_name='PrintSchedule',
        ),
    ]
