# Generated by Django 4.1.7 on 2023-07-26 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0008_rename_printing_printschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='printery.order'),
        ),
    ]
