# Generated by Django 4.1.7 on 2023-07-26 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0009_alter_printschedule_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='printschedule',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printery.order'),
        ),
    ]
