# Generated by Django 4.1.7 on 2023-07-28 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0010_printschedule_id_alter_printschedule_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printschedule',
            old_name='circulation',
            new_name='paper_print_run',
        ),
    ]
