# Generated by Django 4.1.7 on 2023-08-09 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0007_merge_20230526_0126'),
        ('printery', '0011_rename_circulation_printschedule_paper_print_run'),
    ]

    operations = [
    ]
