# Generated by Django 4.1.7 on 2023-08-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0012_merge_20230809_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='printschedule',
            name='parent_day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='printschedule',
            name='position',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='night',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='paper_print_run',
            field=models.IntegerField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='plates_is_done',
            field=models.BooleanField(default=True),
        ),
    ]
