# Generated by Django 4.1.7 on 2023-08-09 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0013_printschedule_parent_day_printschedule_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printschedule',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='printery.order'),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='paper_print_run',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
