# Generated by Django 4.1.7 on 2023-08-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0015_alter_printschedule_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printschedule',
            name='parent_day',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
