# Generated by Django 4.1.7 on 2023-08-29 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0016_alter_printschedule_parent_day'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printschedule',
            old_name='day',
            new_name='sm1',
        ),
        migrations.RemoveField(
            model_name='printschedule',
            name='night',
        ),
        migrations.AddField(
            model_name='printschedule',
            name='rapida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='printschedule',
            name='sm2',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(choices=[(80, '80'), (100, '100'), (105, '105'), (115, '115'), (120, '120'), (130, '130'), (150, '150'), (170, '170'), (200, '200'), (250, '250'), (300, '300')]),
        ),
        migrations.AlterField(
            model_name='paper',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[(None, 'Select...'), ('OFF', 'Офсетная'), ('GL', 'Глянцевая'), ('MAT', 'Матовая'), ('CAR', 'Картон')], max_length=3),
        ),
        migrations.AlterField(
            model_name='part',
            name='color',
            field=models.CharField(blank=True, choices=[(None, 'Select...'), ('4_4', '4+4'), ('4_0', '4+0'), ('1_1', '1+1'), ('1_1', '1+0')], max_length=3),
        ),
    ]
