# Generated by Django 4.1.7 on 2023-09-11 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0017_rename_day_printschedule_sm1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printschedule',
            name='order',
        ),
        migrations.AddField(
            model_name='printschedule',
            name='order_part',
            field=models.ForeignKey(default=811, on_delete=django.db.models.deletion.CASCADE, related_name='printing', to='printery.part'),
            preserve_default=False,
        ),
    ]
