# Generated by Django 4.1.7 on 2023-10-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0018_remove_printschedule_order_printschedule_order_part'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printschedule',
            old_name='paper_print_run',
            new_name='circulation_sheets',
        ),
        migrations.AddField(
            model_name='printschedule',
            name='printed_sheets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, choices=[('BLO', 'Блок'), ('COV', 'Обложка'), ('INS', 'Вклейка'), ('FRZ', 'Форзац')], max_length=3),
        ),
    ]
