# Generated by Django 4.1.7 on 2023-10-03 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0019_rename_paper_print_run_printschedule_circulation_sheets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(blank=True, choices=[(None, 'Select...'), ('BK', 'Книга'), ('CL', 'Календарь'), ('MZ', 'Журнал'), ('NP', 'Газета'), ('FL', 'Флаер'), ('POS', 'Плакат'), ('INS', 'Инструкция')], max_length=3),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, choices=[('BLO', 'блок'), ('COV', 'обложка'), ('INS', 'вклейка'), ('FRZ', 'форзаци')], max_length=3),
        ),
    ]
