# Generated by Django 4.1.7 on 2023-10-03 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0021_alter_part_paper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paper', to='printery.paper'),
        ),
    ]
