# Generated by Django 4.1.7 on 2023-10-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0022_alter_part_paper'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='glossy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paper',
            name='matte',
            field=models.BooleanField(default=False),
        ),
    ]
