# Generated by Django 4.1.7 on 2023-10-06 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0023_paper_glossy_paper_matte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='height',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='paper',
            name='width',
            field=models.IntegerField(blank=True),
        ),
    ]
