# Generated by Django 4.1.7 on 2023-10-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0026_alter_paper_height_alter_paper_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='paper_density',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
