# Generated by Django 4.1.7 on 2023-10-31 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0027_part_paper_density'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='glossy',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='matte',
        ),
        migrations.RemoveField(
            model_name='part',
            name='paper_density',
        ),
        migrations.AlterField(
            model_name='part',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='part_paper', to='printery.paper'),
        ),
    ]
