# Generated by Django 4.1.7 on 2023-11-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0028_remove_paper_glossy_remove_paper_matte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='type',
            field=models.CharField(choices=[('', 'Select...'), ('OFF', 'Офсетная'), ('GL', 'Глянцевая'), ('MAT', 'Матовая'), ('CAR', 'Картон')], max_length=3),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='sm1',
            field=models.BooleanField(default=False),
        ),
    ]
