# Generated by Django 4.1.7 on 2024-04-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0030_alter_part_part_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(blank=True, choices=[(80, '80'), (100, '100'), (105, '105'), (115, '115'), (120, '120'), (130, '130'), (150, '150'), (170, '170'), (200, '200'), (250, '250'), (300, '300')], null=True),
        ),
    ]
