# Generated by Django 4.1.7 on 2024-11-02 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0031_alter_paper_density'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_paper', to='printery.paper'),
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='printed_sheets',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together={('name', 'type', 'density', 'width', 'height')},
        ),
    ]
