# Generated by Django 4.1.7 on 2024-11-02 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0032_alter_part_paper_alter_printschedule_printed_sheets_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paper',
            unique_together=set(),
        ),
    ]
