# Generated by Django 4.1.7 on 2024-11-05 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0033_alter_paper_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='density',
            field=models.IntegerField(blank=True, choices=[(0, 'не известна'), (80, '80'), (100, '100'), (105, '105'), (115, '115'), (120, '120'), (130, '130'), (150, '150'), (170, '170'), (200, '200'), (250, '250'), (300, '300')], null=True),
        ),
    ]
