# Generated by Django 4.1.7 on 2024-12-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0035_alter_part_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='printschedule',
            old_name='print_date',
            new_name='plates_done_date',
        ),
    ]
