# Generated by Django 4.1.7 on 2024-12-03 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0036_rename_print_date_printschedule_plates_done_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='printschedule',
            name='plates_done_date',
        ),
        migrations.RemoveField(
            model_name='printschedule',
            name='plates_is_done',
        ),
        migrations.CreateModel(
            name='Ctp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plates', models.IntegerField(blank=True, null=True)),
                ('plates_bad', models.IntegerField(blank=True, null=True)),
                ('plates_done_date', models.DateField(blank=True, null=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='printery.part')),
            ],
        ),
    ]
