# Generated by Django 4.1.7 on 2024-12-03 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0037_remove_printschedule_plates_done_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctp',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
