# Generated by Django 4.1.7 on 2024-12-06 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0038_ctp_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctp',
            name='part',
        ),
        migrations.AddField(
            model_name='ctp',
            name='printing',
            field=models.ForeignKey(default=222, on_delete=django.db.models.deletion.CASCADE, related_name='ctp', to='printery.printschedule'),
            preserve_default=False,
        ),
    ]
