# Generated by Django 4.1.7 on 2024-12-08 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0039_remove_ctp_part_ctp_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='printschedule',
            name='ctp',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_schedule', to='printery.ctp'),
        ),
        migrations.AlterField(
            model_name='ctp',
            name='printing',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctp_details', to='printery.printschedule'),
        ),
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, choices=[('BLO', 'блок'), ('COV', 'обл.'), ('VKL', 'вкл.'), ('FRZ', 'форзацы')], max_length=3),
        ),
    ]
