# Generated by Django 4.1.7 on 2024-12-08 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0040_printschedule_ctp_alter_ctp_printing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ctp',
            name='printing',
        ),
        migrations.AlterField(
            model_name='printschedule',
            name='ctp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='print_schedule', to='printery.ctp'),
        ),
    ]
