# Generated by Django 4.1.7 on 2024-12-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0041_remove_ctp_printing_alter_printschedule_ctp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctp',
            name='plates_done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
