# Generated by Django 4.1.7 on 2024-12-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0042_alter_ctp_plates_done_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctp',
            name='printing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ctp_related', to='printery.printschedule'),
        ),
    ]
