# Generated by Django 4.1.7 on 2024-12-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0043_ctp_printing'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctp',
            name='status',
            field=models.CharField(choices=[('no_status', 'Без статуса'), ('in_progress', 'В работе'), ('issues', 'Проблемы с заказом'), ('completed', 'Сделан')], default='no_status', max_length=15),
        ),
    ]
