# Generated by Django 4.1.7 on 2024-12-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0046_alter_ctp_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='part_name',
            field=models.CharField(blank=True, choices=[('BLO', 'блок'), ('COV', 'обложка'), ('INS', 'вклейка.'), ('FRZ', 'форзацы')], max_length=3),
        ),
    ]
