version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: printery_db
      POSTGRES_USER: printery_user
      POSTGRES_PASSWORD: P@s$w0rd2025!
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend/backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3001:8000"  # Django на 8000, наружу — 3001
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: printery_db
      DB_USER: printery_user
      DB_PASSWORD: P@s$w0rd2025!
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://localhost:3001"  # для разработки
    volumes:
      - ./frontend:/app

volumes:
  pg_data:
