# Generated by Django 4.1.7 on 2023-02-26 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('printery', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='printery.order'),
        ),
    ]
